// clients/react/src/gemini.jsx
import React, { useState, useEffect, useCallback } from 'react';

// --- Helper Functions ---
/**
 * Gets today's date in YYYY-MM-DD format.
 * @returns {string} Today's date string.
 */
const getTodayDateString = () => {
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, '0'); // Months are 0-indexed
  const day = String(today.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

// --- API Configuration ---
// Replace with your actual API base URL if needed.
const API_BASE_URL = '/api'; 

// --- Validation Logic ---
/**
 * Validates a single form field.
 * @param {string} name - The name of the field to validate.
 * @param {string | number} value - The value of the field.
 * @returns {string} An error message if validation fails, otherwise an empty string.
 */
const validateField = (name, value) => {
  switch (name) {
    case 'title':
      if (!value || value.length < 2 || value.length > 100) {
        return 'Title must be between 2 and 100 characters.';
      }
      return '';
    case 'author':
      if (!value || value.length < 2 || value.length > 60) {
        return 'Author name must be between 2 and 60 characters.';
      }
      return '';
    case 'isbn':
      if (!value || !/^\d{13}$/.test(String(value))) {
        return 'ISBN must contain exactly 13 numeric digits.';
      }
      return '';
    case 'publication_date':
      if (!value) {
        return 'Publication Date is required.'; // Specific message for required
      }
      const inputDate = new Date(value);
      // Check if date string itself is parseable
      if (isNaN(inputDate.getTime())) {
          return 'Invalid date format for Publication Date.'; // Handle unparseable dates
      }
      const today = new Date();
      // Compare dates only, ignoring time part
      inputDate.setHours(0, 0, 0, 0);
      today.setHours(0, 0, 0, 0);
      if (inputDate > today) {
        return 'Publication Date cannot be in the future.';
      }
      return '';
    case 'number_of_pages':
      // Ensure value is treated as a string for consistent checks before parsing
      const stringValue = String(value);
      const numPages = parseInt(stringValue, 10);
      if (
        stringValue === '' || // Check for empty string explicitly
        isNaN(numPages) ||
        numPages < 1 ||
        numPages > 5000 ||
        stringValue !== String(numPages) // Ensures it was a clean integer string (e.g., not "1.2" or "1a")
      ) {
        return 'Number of pages must be between 1 and 5000.';
      }
      return '';
    default:
      return '';
  }
};

/**
 * BookManagement component: Provides a form to add books and a grid to display them.
 */
function Gemini() {
  const initialFormData = {
    title: '',
    author: '',
    isbn: '',
    publication_date: getTodayDateString(),
    number_of_pages: '',
  };

  const initialFormErrors = {
    title: '',
    author: '',
    isbn: '',
    publication_date: '', // Default date is today, which should be valid
    number_of_pages: '',
  };

  const [books, setBooks] = useState([]);
  const [formData, setFormData] = useState(initialFormData);
  const [formErrors, setFormErrors] = useState(initialFormErrors);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [apiError, setApiError] = useState(''); // For displaying API errors

  // Fetch initial books on component mount
  useEffect(() => {
    const fetchBooks = async () => {
      try {
        setApiError('');
        const response = await fetch(`${API_BASE_URL}/books`);
        if (!response.ok) {
          throw new Error(`Failed to fetch books (status: ${response.status})`);
        }
        const data = await response.json();
        setBooks(data); // API is expected to return newest first
      } catch (error) {
        console.error("Error fetching books:", error);
        setApiError(error.message || 'Could not connect to API to fetch books.');
      }
    };
    fetchBooks();
  }, []);

  const handleInputChange = useCallback((e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    // Validate on input/change
    const error = validateField(name, value);
    setFormErrors((prev) => ({ ...prev, [name]: error }));
  }, []);

  const handleBlur = useCallback((e) => {
    const { name, value } = e.target;
    // Validate on blur
    const error = validateField(name, value);
    setFormErrors((prev) => ({ ...prev, [name]: error }));
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setApiError(''); // Clear previous API errors

    // Perform a final validation pass for all fields
    let currentFormErrors = {};
    let isFormCurrentlyValid = true;
    for (const key in formData) {
        const error = validateField(key, formData[key]);
        currentFormErrors[key] = error;
        if (error) {
            isFormCurrentlyValid = false;
        }
    }
    setFormErrors(currentFormErrors);

    if (!isFormCurrentlyValid) {
        return; // Stop submission if validation fails
    }

    setIsSubmitting(true);
    const bookDataToSubmit = {
        ...formData,
        number_of_pages: parseInt(formData.number_of_pages, 10),
    };

    try {
      const response = await fetch(`${API_BASE_URL}/books`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(bookDataToSubmit),
      });

      if (!response.ok) {
        let errorData;
        try {
            errorData = await response.json();
        } catch (jsonParseError) {
            // Fallback if response is not JSON
            errorData = { message: `Server error: ${response.status}` };
        }
        throw new Error(errorData?.message || `Failed to add book (status: ${response.status})`);
      }

      const newBook = await response.json();
      setBooks((prevBooks) => [newBook, ...prevBooks]); // Add new book to the top
      setFormData(initialFormData); // Clear form
      setFormErrors(initialFormErrors); // Reset errors to initial (empty for most fields)

    } catch (error) {
      console.error("Error adding book:", error);
      setApiError(error.message || 'An unexpected error occurred while adding the book.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Derived state for submit button disability
  const isSubmitButtonDisabled = () => {
    // Check if any field (all are effectively required by their validation rules if empty) is empty
    if (Object.values(formData).some(value => value === '')) {
        // Exception for publication_date if it's valid (though it defaults to non-empty)
        if (formData.publication_date === '' && validateField('publication_date', '') !== '') {
            return true;
        }
        // Check other fields for emptiness
        for (const key in formData) {
            if (key !== 'publication_date' && formData[key] === '') {
                return true;
            }
        }
    }
    // Check if there are any validation errors displayed
    if (Object.values(formErrors).some(error => error !== '')) {
        return true;
    }
    return isSubmitting;
  };
  
  // Minimal inline styles for better readability without CSS files
  const styles = {
    container: { fontFamily: 'Arial, sans-serif', maxWidth: '800px', margin: '0 auto', padding: '20px' },
    heading: { color: '#333' },
    form: { marginBottom: '30px', padding: '20px', border: '1px solid #eee', borderRadius: '8px', backgroundColor: '#f9f9f9' },
    formSectionHeading: { marginTop: '0', borderBottom: '1px solid #ddd', paddingBottom: '10px', marginBottom: '20px' },
    formField: { marginBottom: '15px' },
    label: { display: 'block', marginBottom: '5px', fontWeight: 'bold', fontSize: '0.9em' },
    input: { width: 'calc(100% - 16px)', padding: '8px', border: '1px solid #ccc', borderRadius: '4px', boxSizing: 'border-box' },
    error: { color: 'red', fontSize: '0.85em', marginTop: '4px' },
    apiError: { color: 'red', fontSize: '0.9em', marginTop: '10px', padding: '10px', border: '1px solid red', borderRadius: '4px', backgroundColor: '#ffe0e0'},
    button: { padding: '10px 15px', backgroundColor: '#007bff', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '1em' },
    disabledButton: { backgroundColor: '#ccc', cursor: 'not-allowed' },
    hr: { margin: '30px 0', border: '0', borderTop: '1px solid #eee' },
    gridContainer: { marginTop: '20px' },
    table: { width: '100%', borderCollapse: 'collapse', fontSize: '0.9em' },
    thTd: { border: '1px solid #ddd', padding: '10px', textAlign: 'left' },
    th: { backgroundColor: '#f0f0f0', fontWeight: 'bold' },
    noBooksRow: { textAlign: 'center', fontStyle: 'italic', color: '#777' }
  };

  return (
    <div style={styles.container}>
      <h1 style={styles.heading}>📚 Book Management</h1>

      <form onSubmit={handleSubmit} data-testid="book-form" style={styles.form}>
        <h2 style={styles.formSectionHeading}>Add New Book</h2>

        {apiError && <div data-testid="error-api" style={styles.apiError}>{apiError}</div>}

        <div style={styles.formField}>
          <label htmlFor="title" style={styles.label}>Book Title</label>
          <input
            type="text"
            id="title"
            name="title"
            value={formData.title}
            onChange={handleInputChange}
            onBlur={handleBlur}
            placeholder="Enter book title"
            data-testid="input-title"
            style={styles.input}
            aria-describedby={formErrors.title ? "error-title" : undefined}
            aria-invalid={!!formErrors.title}
          />
          {formErrors.title && <div id="error-title" data-testid="error-title" style={styles.error} role="alert">{formErrors.title}</div>}
        </div>

        <div style={styles.formField}>
          <label htmlFor="author" style={styles.label}>Author Name</label>
          <input
            type="text"
            id="author"
            name="author"
            value={formData.author}
            onChange={handleInputChange}
            onBlur={handleBlur}
            placeholder="Enter author name"
            data-testid="input-author"
            style={styles.input}
            aria-describedby={formErrors.author ? "error-author" : undefined}
            aria-invalid={!!formErrors.author}
          />
          {formErrors.author && <div id="error-author" data-testid="error-author" style={styles.error} role="alert">{formErrors.author}</div>}
        </div>

        <div style={styles.formField}>
          <label htmlFor="isbn" style={styles.label}>ISBN Number</label>
          <input
            type="text"
            id="isbn"
            name="isbn"
            value={formData.isbn}
            onChange={handleInputChange}
            onBlur={handleBlur}
            placeholder="Enter 13-digit ISBN number"
            data-testid="input-isbn"
            style={styles.input}
            aria-describedby={formErrors.isbn ? "error-isbn" : undefined}
            aria-invalid={!!formErrors.isbn}
          />
          {formErrors.isbn && <div id="error-isbn" data-testid="error-isbn" style={styles.error} role="alert">{formErrors.isbn}</div>}
        </div>

        <div style={styles.formField}>
          <label htmlFor="publication_date" style={styles.label}>Publication Date</label>
          <input
            type="date"
            id="publication_date"
            name="publication_date"
            value={formData.publication_date}
            onChange={handleInputChange}
            onBlur={handleBlur}
            data-testid="input-publication-date"
            style={styles.input}
            aria-describedby={formErrors.publication_date ? "error-publication-date" : undefined}
            aria-invalid={!!formErrors.publication_date}
          />
          {formErrors.publication_date && <div id="error-publication-date" data-testid="error-publication-date" style={styles.error} role="alert">{formErrors.publication_date}</div>}
        </div>

        <div style={styles.formField}>
          <label htmlFor="number_of_pages" style={styles.label}>Number of Pages</label>
          <input
            type="text" // Using text to better control input and rely on custom validation for integer.
                       // type="number" can have tricky behavior with empty strings or non-integer values.
            id="number_of_pages"
            name="number_of_pages"
            value={formData.number_of_pages}
            onChange={handleInputChange}
            onBlur={handleBlur}
            placeholder="Enter number of pages"
            data-testid="input-pages"
            style={styles.input}
            inputMode="numeric" // Hint for numeric keyboard on mobile
            pattern="[0-9]*"    // Basic pattern hint
            aria-describedby={formErrors.number_of_pages ? "error-pages" : undefined}
            aria-invalid={!!formErrors.number_of_pages}
          />
          {formErrors.number_of_pages && <div id="error-pages" data-testid="error-pages" style={styles.error} role="alert">{formErrors.number_of_pages}</div>}
        </div>

        <button
          type="submit"
          data-testid="btn-submit-book"
          disabled={isSubmitButtonDisabled()}
          style={{...styles.button, ...(isSubmitButtonDisabled() ? styles.disabledButton : {})}}
        >
          {isSubmitting ? 'Adding...' : 'Add Book'}
        </button>
      </form>

      <hr style={styles.hr} />
      
      <div style={styles.gridContainer}>
        <h2 style={styles.heading}>📖 Book List</h2>
        <div data-testid="data-grid-books">
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={{...styles.thTd, ...styles.th}}>ID</th>
                <th style={{...styles.thTd, ...styles.th}}>Title</th>
                <th style={{...styles.thTd, ...styles.th}}>Author</th>
                <th style={{...styles.thTd, ...styles.th}}>ISBN</th>
                <th style={{...styles.thTd, ...styles.th}}>Publication Date</th>
                <th style={{...styles.thTd, ...styles.th}}>Pages</th>
              </tr>
            </thead>
            <tbody>
              {books.length === 0 ? (
                <tr>
                  <td colSpan="6" style={{...styles.thTd, ...styles.noBooksRow}}>
                    {apiError && apiError.includes("fetch") ? apiError : "No books available. Add one above!"}
                  </td>
                </tr>
              ) : (
                books.map((book) => (
                  <tr key={book.id} data-testid={`data-grid-row-${book.id}`}>
                    <td data-testid={`data-grid-cell-id-${book.id}`} style={styles.thTd}>{book.id}</td>
                    <td data-testid={`data-grid-cell-title-${book.id}`} style={styles.thTd}>{book.title}</td>
                    <td data-testid={`data-grid-cell-author-${book.id}`} style={styles.thTd}>{book.author}</td>
                    <td data-testid={`data-grid-cell-isbn-${book.id}`} style={styles.thTd}>{book.isbn}</td>
                    <td data-testid={`data-grid-cell-publication-date-${book.id}`} style={styles.thTd}>
                      {book.publication_date} {/* API provides YYYY-MM-DD */}
                    </td>
                    <td data-testid={`data-grid-cell-pages-${book.id}`} style={styles.thTd}>{book.number_of_pages}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default Gemini;

// clients/angular/src/app/gemini.component.ts
import { Component, OnInit, inject, OnDestroy } from '@angular/core';
import { CommonModule, formatDate } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, AbstractControl, ValidationErrors } from '@angular/forms';
import { HttpClient, HttpClientModule, HttpErrorResponse } from '@angular/common/http';
import { Subscription, throwError } from 'rxjs';
import { catchError, finalize } from 'rxjs/operators';

// --- INTERFACE ---
interface Book {
  id?: number; // Optional: not present for new books before submission, assigned by backend
  title: string;
  author: string;
  isbn: string;
  publication_date: string; // YYYY-MM-DD
  number_of_pages: number;
}

// --- CUSTOM VALIDATOR ---
/**
 * Custom validator to check if the date is not in the future.
 * @param control - The AbstractControl to validate.
 * @returns ValidationErrors | null - An error object if invalid, otherwise null.
 */
function notFutureDateValidator(control: AbstractControl): ValidationErrors | null {
  if (!control.value) {
    return null; // Let 'required' validator handle empty values
  }
  const inputDate = new Date(control.value);
  const today = new Date();

  // Normalize by setting time to 00:00:00.000 to compare dates only
  inputDate.setHours(0, 0, 0, 0);
  today.setHours(0, 0, 0, 0);

  if (inputDate > today) {
    return { futureDate: true };
  }
  return null;
}

// --- COMPONENT ---
@Component({
  selector: 'app-gemini',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    HttpClientModule // For a standalone component, HttpClientModule needs to be imported.
                     // In a larger app, you might use provideHttpClient() in bootstrapApplication.
  ],
  template: `
    <div class="book-management-container">
      <section class="form-section">
        <h2>Add New Book</h2>
        <form [formGroup]="bookForm" (ngSubmit)="onSubmit()">
          <div class="form-field">
            <label for="title">Book Title</label>
            <input id="title" type="text" formControlName="title" data-testid="input-title" placeholder="Enter book title">
            <div *ngIf="isControlInvalid('title')" class="error-message" data-testid="error-title">
              <span *ngIf="bookForm.get('title')?.errors?.['required']">Title is required.</span>
              <span *ngIf="bookForm.get('title')?.errors?.['minlength'] || bookForm.get('title')?.errors?.['maxlength']">Title must be between 2 and 100 characters.</span>
            </div>
          </div>

          <div class="form-field">
            <label for="author">Author Name</label>
            <input id="author" type="text" formControlName="author" data-testid="input-author" placeholder="Enter author name">
            <div *ngIf="isControlInvalid('author')" class="error-message" data-testid="error-author">
              <span *ngIf="bookForm.get('author')?.errors?.['required']">Author name is required.</span>
              <span *ngIf="bookForm.get('author')?.errors?.['minlength'] || bookForm.get('author')?.errors?.['maxlength']">Author name must be between 2 and 60 characters.</span>
            </div>
          </div>

          <div class="form-field">
            <label for="isbn">ISBN Number</label>
            <input id="isbn" type="text" formControlName="isbn" data-testid="input-isbn" placeholder="Enter 13-digit ISBN number">
            <div *ngIf="isControlInvalid('isbn')" class="error-message" data-testid="error-isbn">
              <span *ngIf="bookForm.get('isbn')?.errors?.['required']">ISBN is required.</span>
              <span *ngIf="bookForm.get('isbn')?.errors?.['pattern']">ISBN must contain exactly 13 numeric digits.</span>
            </div>
          </div>

          <div class="form-field">
            <label for="publication_date">Publication Date</label>
            <input id="publication_date" type="date" formControlName="publication_date" data-testid="input-publication-date">
            <div *ngIf="isControlInvalid('publication_date')" class="error-message" data-testid="error-publication-date">
              <span *ngIf="bookForm.get('publication_date')?.errors?.['required']">Publication Date is required.</span>
              <span *ngIf="bookForm.get('publication_date')?.errors?.['futureDate']">Publication Date cannot be in the future.</span>
            </div>
          </div>

          <div class="form-field">
            <label for="number_of_pages">Number of Pages</label>
            <input id="number_of_pages" type="number" formControlName="number_of_pages" data-testid="input-pages" placeholder="Enter number of pages">
            <div *ngIf="isControlInvalid('number_of_pages')" class="error-message" data-testid="error-pages">
              <span *ngIf="bookForm.get('number_of_pages')?.errors?.['required']">Number of pages is required.</span>
              <span *ngIf="bookForm.get('number_of_pages')?.errors?.['min'] || bookForm.get('number_of_pages')?.errors?.['max']">Number of pages must be between 1 and 5000.</span>
            </div>
          </div>

          <button type="submit" data-testid="btn-submit-book" [disabled]="bookForm.invalid || submitting">Add Book</button>
          <div *ngIf="submissionError" class="error-message submission-error">
            Error submitting book: {{ submissionError }}
          </div>
        </form>
      </section>

      <hr class="section-divider">

      <section class="grid-section">
        <h2>Book Collection</h2>
        <div *ngIf="isLoadingBooks" class="loading-message">Loading books...</div>
        <div *ngIf="!isLoadingBooks && books.length === 0 && !initialLoadError" class="empty-message">No books in the collection yet. Add one above!</div>
        <div *ngIf="initialLoadError" class="error-message">Failed to load books: {{ initialLoadError }}</div>

        <div *ngIf="!isLoadingBooks && books.length > 0" class="grid-container" data-testid="data-grid-books">
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Publication Date</th>
                <th>Pages</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let book of books" [attr.data-testid]="'data-grid-row-' + book.id">
                <td [attr.data-testid]="'data-grid-cell-id-' + book.id">{{ book.id }}</td>
                <td [attr.data-testid]="'data-grid-cell-title-' + book.id">{{ book.title }}</td>
                <td [attr.data-testid]="'data-grid-cell-author-' + book.id">{{ book.author }}</td>
                <td [attr.data-testid]="'data-grid-cell-isbn-' + book.id">{{ book.isbn }}</td>
                <td [attr.data-testid]="'data-grid-cell-publication-date-' + book.id">{{ book.publication_date }}</td>
                <td [attr.data-testid]="'data-grid-cell-pages-' + book.id">{{ book.number_of_pages }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  `,
  styles: [`
    .book-management-container {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 20px auto;
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 8px;
      background-color: #f9f9f9;
    }
    h2 {
      color: #333;
      border-bottom: 2px solid #007bff;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    .form-section, .grid-section {
      margin-bottom: 30px;
    }
    .form-field {
      margin-bottom: 15px;
    }
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
      color: #555;
    }
    input[type="text"],
    input[type="date"],
    input[type="number"] {
      width: calc(100% - 22px); /* Full width minus padding and border */
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      font-size: 1em;
    }
    input.ng-invalid.ng-touched {
      border-color: #dc3545; /* Red border for invalid touched fields */
    }
    .error-message {
      color: #dc3545; /* Red color for error messages */
      font-size: 0.875em;
      margin-top: 5px;
    }
    .submission-error {
        margin-top: 10px;
    }
    button[type="submit"] {
      padding: 10px 20px;
      background-color: #007bff;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 1em;
      transition: background-color 0.3s ease;
    }
    button[type="submit"]:hover:not(:disabled) {
      background-color: #0056b3;
    }
    button[type="submit"]:disabled {
      background-color: #ccc;
      cursor: not-allowed;
    }
    .section-divider {
      border: 0;
      height: 1px;
      background-color: #ddd;
      margin: 30px 0;
    }
    .grid-container {
      overflow-x: auto; /* For responsiveness on smaller screens */
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 10px;
      text-align: left;
      vertical-align: middle;
    }
    th {
      background-color: #e9ecef;
      font-weight: bold;
      color: #333;
    }
    tr:nth-child(even) {
      background-color: #f8f9fa;
    }
    .loading-message, .empty-message {
        text-align: center;
        padding: 20px;
        color: #555;
        font-style: italic;
    }
  `]
})
export class GeminiComponent implements OnInit, OnDestroy {
  bookForm!: FormGroup;
  books: Book[] = [];
  isLoadingBooks = false;
  initialLoadError: string | null = null;
  submitting = false;
  submissionError: string | null = null;

  private readonly apiBaseUrl = '/api'; // Replace with actual API base URL if different
  private http = inject(HttpClient);
  private fb = inject(FormBuilder);
  private subscriptions: Subscription = new Subscription();

  ngOnInit(): void {
    this.initForm();
    this.loadBooks();
  }

  private initForm(): void {
    this.bookForm = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(100)]],
      author: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(60)]],
      isbn: ['', [Validators.required, Validators.pattern('^[0-9]{13}$')]], // Exactly 13 numeric digits
      publication_date: [this.getTodayDateString(), [Validators.required, notFutureDateValidator]],
      number_of_pages: ['', [Validators.required, Validators.min(1), Validators.max(5000)]]
    });
  }

  private getTodayDateString(): string {
    return formatDate(new Date(), 'yyyy-MM-dd', 'en-US');
  }

  isControlInvalid(controlName: string): boolean {
    const control = this.bookForm.get(controlName);
    return !!(control && control.invalid && (control.dirty || control.touched));
  }

  private loadBooks(): void {
    this.isLoadingBooks = true;
    this.initialLoadError = null;
    const booksSub = this.http.get<Book[]>(`${this.apiBaseUrl}/books`)
      .pipe(
        catchError((error: HttpErrorResponse) => {
          this.initialLoadError = this.formatErrorMessage(error);
          return throwError(() => new Error('Failed to load books. ' + this.initialLoadError));
        }),
        finalize(() => this.isLoadingBooks = false)
      )
      .subscribe({
        next: (loadedBooks) => {
          this.books = loadedBooks; // Assuming API returns newest first as per spec
        },
        error: (err) => console.error(err) // Error already handled by catchError for UI
      });
    this.subscriptions.add(booksSub);
  }

  onSubmit(): void {
    if (this.bookForm.invalid) {
      // Mark all fields as touched to display validation errors if not already shown
      this.bookForm.markAllAsTouched();
      return;
    }

    this.submitting = true;
    this.submissionError = null;
    const newBookData = this.bookForm.value;

    const createSub = this.http.post<Book>(`${this.apiBaseUrl}/books`, newBookData)
      .pipe(
        catchError((error: HttpErrorResponse) => {
          this.submissionError = this.formatErrorMessage(error);
          return throwError(() => new Error('Failed to submit book. ' + this.submissionError));
        }),
        finalize(() => this.submitting = false)
      )
      .subscribe({
        next: (createdBook) => {
          this.books.unshift(createdBook); // Add new book to the top of the grid
          this.resetForm();
        },
        error: (err) => console.error(err) // Error already handled by catchError for UI
      });
    this.subscriptions.add(createSub);
  }

  private resetForm(): void {
    this.bookForm.reset();
    this.bookForm.patchValue({
      publication_date: this.getTodayDateString() // Reset date to today
    });
    // Manually reset touched/dirty state if needed for specific UI behavior after reset
    Object.keys(this.bookForm.controls).forEach(key => {
        this.bookForm.get(key)?.setErrors(null) ;
        this.bookForm.get(key)?.markAsPristine();
        this.bookForm.get(key)?.markAsUntouched();
    });
    this.bookForm.updateValueAndValidity();
  }

  private formatErrorMessage(error: HttpErrorResponse): string {
    if (error.error instanceof ErrorEvent) {
      // Client-side or network error
      return `Network error: ${error.error.message}`;
    } else {
      // Backend returned an unsuccessful response code.
      // The response body may contain clues as to what went wrong.
      let message = `Server error (status ${error.status}): `;
      if (typeof error.error === 'string') {
        message += error.error;
      } else if (error.error && typeof error.error.message === 'string') {
        message += error.error.message;
      } else if (error.message) {
        message += error.message;
      } else {
        message += 'Unknown server error.';
      }
      return message;
    }
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }
}
