// clients/react/src/gemini-diffusion.jsx
import React from 'react';
const { useState, useEffect } = React;
const API_URL = 'http://localhost:3000/books'; // Assuming a local JSON Server instance

const validateBook = (book) => {
    const errors = {};
    if (!book.title || book.title.length < 2 || book.title.length > 100) {
        errors.title = 'Title must be between 2 and 100 characters.';
    }
    if (!book.author || book.author.length < 2 || book.author.length > 60) {
        errors.author = 'Author name must be between 2 and 60 characters.';
    }
    if (!book.isbn || !/^\d{13}$/.test(book.isbn)) {
        errors.isbn = 'ISBN must contain exactly 13 numeric digits.';
    }
    if (!book.publication_date) {
        errors.publication_date = 'Publication Date is required.';
    } else {
        const pubDate = new Date(book.publication_date);
        const today = new Date();
        today.setHours(0, 0, 0, 0); // Reset time for comparison
        if (pubDate > today) {
            errors.publication_date = 'Publication Date cannot be in the future.';
        }
    }
    if (!book.number_of_pages || !Number.isInteger(book.number_of_pages) || book.number_of_pages < 1 || book.number_of_pages > 5000) {
        errors.number_of_pages = 'Number of pages must be between 1 and 5000.';
    }
    return errors;
};

const BookForm = ({ onAddBook }) => {
    const [book, setBook] = useState({
        title: '',
        author: '',
        isbn: '',
        publication_date: new Date().toISOString().split('T')[0], // Default to today
        number_of_pages: '',
    });
    const [errors, setErrors] = useState({});

    const handleChange = (e) => {
        const { name, value } = e.target;
        setBook(prev => ({ ...prev, [name]: value }));
        // Real-time validation on input change
        const newErrors = validateBook({ ...book, [name]: value });
        setErrors(prev => ({ ...prev, [name]: newErrors[name] }));
    };

    const validateForm = () => {
        const newErrors = validateBook(book);
        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (validateForm()) {
            await onAddBook(book);
            setBook({
                title: '',
                author: '',
                isbn: '',
                publication_date: new Date().toISOString().split('T')[0],
                number_of_pages: '',
            });
            setErrors({}); // Clear errors after successful submission
        }
    };

    const isFormValid = Object.keys(errors).length === 0 && Object.values(book).every(val => val !== '');

    return (
        <div className="form-container">
            <h2>Add New Book</h2>
            <form onSubmit={handleSubmit}>
                <div className="form-group">
                    <label htmlFor="input-title">Book Title</label>
                    <input
                        type="text"
                        id="input-title"
                        name="title"
                        data-testid="input-title"
                        value={book.title}
                        onChange={handleChange}
                        onBlur={handleChange}
                        placeholder="Enter book title"
                    />
                    {errors.title && <p className="error-message" data-testid="error-title">{errors.title}</p>}
                </div>
                <div className="form-group">
                    <label htmlFor="input-author">Author Name</label>
                    <input
                        type="text"
                        id="input-author"
                        name="author"
                        data-testid="input-author"
                        value={book.author}
                        onChange={handleChange}
                        onBlur={handleChange}
                        placeholder="Enter author name"
                    />
                    {errors.author && <p className="error-message" data-testid="error-author">{errors.author}</p>}
                </div>
                <div className="form-group">
                    <label htmlFor="input-isbn">ISBN Number</label>
                    <input
                        type="text"
                        id="input-isbn"
                        name="isbn"
                        data-testid="input-isbn"
                        value={book.isbn}
                        onChange={handleChange}
                        onBlur={handleChange}
                        placeholder="Enter 13-digit ISBN number"
                    />
                    {errors.isbn && <p className="error-message" data-testid="error-isbn">{errors.isbn}</p>}
                </div>
                <div className="form-group">
                    <label htmlFor="input-publication-date">Publication Date</label>
                    <input
                        type="date"
                        id="input-publication-date"
                        name="publication_date"
                        data-testid="input-publication-date"
                        value={book.publication_date}
                        onChange={handleChange}
                        onBlur={handleChange}
                    />
                    {errors.publication_date && <p className="error-message" data-testid="error-publication-date">{errors.publication_date}</p>}
                </div>
                <div className="form-group">
                    <label htmlFor="input-pages">Number of Pages</label>
                    <input
                        type="number"
                        id="input-pages"
                        name="number_of_pages"
                        data-testid="input-pages"
                        value={book.number_of_pages}
                        onChange={handleChange}
                        onBlur={handleChange}
                        placeholder="Enter number of pages"
                    />
                    {errors.number_of_pages && <p className="error-message" data-testid="error-pages">{errors.number_of_pages}</p>}
                </div>
                <button type="submit" data-testid="btn-submit-book" disabled={!isFormValid}>
                    Add Book
                </button>
            </form>
        </div>
    );
};

const BookDataGrid = ({ books }) => {
    if (!books || books.length === 0) {
        return <p>No books added yet.</p>;
    }

    return (
        <table className="data-grid" data-testid="data-grid-books">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th>Publication Date</th>
                    <th>Pages</th>
                </tr>
            </thead>
            <tbody>
                {books.map((book) => (
                    <tr key={book.id} data-testid={`data-grid-row-${book.id}`}>
                        <td data-testid={`data-grid-cell-id-${book.id}`}>{book.id}</td>
                        <td data-testid={`data-grid-cell-title-${book.id}`}>{book.title}</td>
                        <td data-testid={`data-grid-cell-author-${book.id}`}>{book.author}</td>
                        <td data-testid={`data-grid-cell-isbn-${book.id}`}>{book.isbn}</td>
                        <td data-testid={`data-grid-cell-publication-date-${book.id}`}>{book.publication_date}</td>
                        <td data-testid={`data-grid-cell-pages-${book.id}`}>{book.number_of_pages}</td>
                    </tr>
                ))}
            </tbody>
        </table>
    );
};

const GeminiDiffusion = () => {
    const [books, setBooks] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchBooks = async () => {
            try {
                const response = await fetch(API_URL);
                if (!response.ok) {
                    throw new Error(`HTTP error! status: ${response.status}`);
                }
                const data = await response.json();
                setBooks(data);
            } catch (err) {
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };

        fetchBooks();
    }, []);

    const handleAddBook = async (newBook) => {
        try {
            const response = await fetch(API_URL, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(newBook),
            });
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            const createdBook = await response.json();
            // Add the new book to the beginning of the list
            setBooks(prevBooks => [createdBook, ...prevBooks]);
        } catch (err) {
            setError(err.message);
            console.error("Failed to add book:", err);
        }
    };

    if (loading) {
        return <p>Loading books...</p>;
    }

    if (error) {
        return <p>Error fetching books: {error}</p>;
    }

    return (
        <div>
            <BookForm onAddBook={handleAddBook} />
            <BookDataGrid books={books} />
        </div>
    );
};

export default GeminiDiffusion;

// clients/angular/LLMTest/src/app/geminidiffusion.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';

interface Book {
  id: number;
  title: string;
  author: string;
  isbn: string;
  publication_date: string;
  number_of_pages: number;
}

@Component({
  selector: 'app-gemini-diffusion',
  standalone: true,
  imports: [ReactiveFormsModule, HttpClientModule, CommonModule],
  template: `
    <div class="container mx-auto p-4">
      <h1 class="text-2xl font-bold mb-4">Book Management</h1>

      <!-- Book Entry Form -->
      <form [formGroup]="bookForm" (ngSubmit)="onSubmit()" class="mb-8 p-4 border rounded-lg shadow-md">
        <h2 class="text-xl font-semibold mb-4">Add New Book</h2>

        <div class="mb-4">
          <label for="input-title" class="block text-sm font-medium text-gray-700">Book Title</label>
          <input
            type="text"
            id="input-title"
            formControlName="title"
            data-testid="input-title"
            placeholder="Enter book title"
            class="mt-1 block w-full border border-gray-300 rounded-md"
          />
          <div
            data-testid="error-title"
            *ngIf="bookForm.get('title')?.invalid && (bookForm.get('title')?.touched || bookForm.get('title')?.dirty)"
            class="text-red-500 text-sm mt-1"
          >
            <div *ngIf="bookForm.get('title')?.errors?.['required']">Title is required.</div>
            <div *ngIf="bookForm.get('title')?.errors?.['minlength'] || bookForm.get('title')?.errors?.['maxlength']">
              Title must be between 2 and 100 characters.
            </div>
          </div>
        </div>

        <div class="mb-4">
          <label for="input-author" class="block text-sm font-medium text-gray-700">Author Name</label>
          <input
            type="text"
            id="input-author"
            formControlName="author"
            data-testid="input-author"
            placeholder="Enter author name"
            class="mt-1 block w-full border border-gray-300 rounded-md"
          />
          <div
            data-testid="error-author"
            *ngIf="bookForm.get('author')?.invalid && (bookForm.get('author')?.touched || bookForm.get('author')?.dirty)"
            class="text-red-500 text-sm mt-1"
          >
            <div *ngIf="bookForm.get('author')?.errors?.['required']">Author name is required.</div>
            <div *ngIf="bookForm.get('author')?.errors?.['minlength'] || bookForm.get('author')?.errors?.['maxlength']">
              Author name must be between 2 and 60 characters.
            </div>
          </div>
        </div>

        <div class="mb-4">
          <label for="input-isbn" class="block text-sm font-medium text-gray-700">ISBN Number</label>
          <input
            type="text"
            id="input-isbn"
            formControlName="isbn"
            data-testid="input-isbn"
            placeholder="Enter 13-digit ISBN number"
            class="mt-1 block w-full border border-gray-300 rounded-md"
          />
          <div
            data-testid="error-isbn"
            *ngIf="bookForm.get('isbn')?.invalid && (bookForm.get('isbn')?.touched || bookForm.get('isbn')?.dirty)"
            class="text-red-500 text-sm mt-1"
          >
            <div *ngIf="bookForm.get('isbn')?.errors?.['required']">ISBN is required.</div>
            <div *ngIf="bookForm.get('isbn')?.errors?.['pattern']">ISBN must contain exactly 13 numeric digits.</div>
          </div>
        </div>

        <div class="mb-4">
          <label for="input-publication-date" class="block text-sm font-medium text-gray-700">Publication Date</label>
          <input
            type="date"
            id="input-publication-date"
            formControlName="publication_date"
            data-testid="input-publication-date"
            class="mt-1 block w-full border border-gray-300 rounded-md"
          />
          <div
            data-testid="error-publication-date"
            *ngIf="bookForm.get('publication_date')?.invalid && (bookForm.get('publication_date')?.touched || bookForm.get('publication_date')?.dirty)"
            class="text-red-500 text-sm mt-1"
          >
            <div *ngIf="bookForm.get('publication_date')?.errors?.['required']">Publication date is required.</div>
            <div *ngIf="bookForm.get('publication_date')?.errors?.['invalidDate']">Publication Date cannot be in the future.</div>
          </div>
        </div>

        <div class="mb-4">
          <label for="input-pages" class="block text-sm font-medium text-gray-700">Number of Pages</label>
          <input
            type="number"
            id="input-pages"
            formControlName="number_of_pages"
            data-testid="input-pages"
            placeholder="Enter number of pages"
            class="mt-1 block w-full border border-gray-300 rounded-md"
          />
          <div
            data-testid="error-pages"
            *ngIf="bookForm.get('number_of_pages')?.invalid && (bookForm.get('number_of_pages')?.touched || bookForm.get('number_of_pages')?.dirty)"
            class="text-red-500 text-sm mt-1"
          >
            <div *ngIf="bookForm.get('number_of_pages')?.errors?.['required']">Number of pages is required.</div>
            <div *ngIf="bookForm.get('number_of_pages')?.errors?.['min'] || bookForm.get('number_of_pages')?.errors?.['max']">
              Number of pages must be between 1 and 5000.
            </div>
          </div>
        </div>

        <button
          type="submit"
          data-testid="btn-submit-book"
          [disabled]="bookForm.invalid"
          class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 disabled:bg-gray-400 disabled:cursor-not-allowed"
        >
          Add Book
        </button>
      </form>

      <!-- Book Data Grid -->
      <h2 class="text-xl font-semibold mb-4">Books</h2>
      <table data-testid="data-grid-books" class="w-full border-collapse">
        <thead>
          <tr class="bg-gray-200">
            <th class="border px-4 py-2 text-left">ID</th>
            <th class="border px-4 py-2 text-left">Title</th>
            <th class="border px-4 py-2 text-left">Author</th>
            <th class="border px-4 py-2 text-left">ISBN</th>
            <th class="border px-4 py-2 text-left">Publication Date</th>
            <th class="border px-4 py-2 text-left">Pages</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let book of books" [attr.data-testid]="'data-grid-row-' + book.id">
            <td class="border px-4 py-2" [attr.data-testid]="'data-grid-cell-id-' + book.id">{{ book.id }}</td>
            <td class="border px-4 py-2" [attr.data-testid]="'data-grid-cell-title-' + book.id">{{ book.title }}</td>
            <td class="border px-4 py-2" [attr.data-testid]="'data-grid-cell-author-' + book.id">{{ book.author }}</td>
            <td class="border px-4 py-2" [attr.data-testid]="'data-grid-cell-isbn-' + book.id">{{ book.isbn }}</td>
            <td class="border px-4 py-2" [attr.data-testid]="'data-grid-cell-publication-date-' + book.id">{{ book.publication_date }}</td>
            <td class="border px-4 py-2" [attr.data-testid]="'data-grid-cell-pages-' + book.id">{{ book.number_of_pages }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
  styles: []
})
export class GeminiDiffusionComponent implements OnInit {
  bookForm: FormGroup;
  books: Book[] = [];
  private apiUrl = 'http://localhost:3000'; // Replace with your API URL if needed

  constructor(private fb: FormBuilder, private http: HttpClient) {
    this.bookForm = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(100)]],
      author: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(60)]],
      isbn: ['', [Validators.required, Validators.pattern(/^\d{13}$/)]],
      publication_date: ['', [Validators.required, this.futureDateValidator]],
      number_of_pages: ['', [Validators.required, Validators.min(1), Validators.max(5000)]],
    });
  }

  ngOnInit(): void {
    this.loadBooks();
    // Set default publication date to today
    const today = new Date().toISOString().split('T')[0];
    this.bookForm.get('publication_date')?.setValue(today);
  }

  futureDateValidator(control: any): { [key: string]: any } | null {
    const inputDate = control.value;
    if (!inputDate) {
      return null;
    }
    const selectedDate = new Date(inputDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0); // Reset time for accurate comparison
    selectedDate.setHours(0, 0, 0, 0);

    if (selectedDate > today) {
      return { 'invalidDate': true };
    }
    return null;
  }

  loadBooks(): void {
    this.http.get<Book[]>(`${this.apiUrl}/books`).subscribe({
      next: (data) => {
        // Sort books by ID (newest first)
        this.books = data.sort((a, b) => b.id - a.id);
      },
      error: (error) => {
        console.error('Error fetching books:', error);
      }
    });
  }

  onSubmit(): void {
    if (this.bookForm.invalid) {
      return; // Stop submission if the form is invalid
    }

    const newBook = this.bookForm.value;

    this.http.post<Book>(`${this.apiUrl}/books`, newBook).subscribe({
      next: (createdBook) => {
        // Add the new book to the beginning of the list
        this.books.unshift(createdBook);
        // Clear the form
        this.bookForm.reset();
        // Reset publication date to today after submission
        const today = new Date().toISOString().split('T')[0];
        this.bookForm.get('publication_date')?.setValue(today);
      },
      error: (error) => {
        console.error('Error adding book:', error);
      }
    });
  }
}
