// clients/angular/LLMTest/src/app/claude.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Observable } from 'rxjs';

interface Book {
  id?: number;
  title: string;
  author: string;
  isbn: string;
  publication_date: string;
  number_of_pages: number;
}

interface ValidationErrors {
  title?: string;
  author?: string;
  isbn?: string;
  publication_date?: string;
  number_of_pages?: string;
}

@Component({
  selector: 'app-claude',
  standalone: true,
  imports: [CommonModule, FormsModule, HttpClientModule],
  template: `
    <div class="container">
      <h1>Book Management System</h1>

      <!-- Book Entry Form -->
      <form (ngSubmit)="onSubmit()" class="book-form">
        <h2>Add New Book</h2>

        <!-- Title Field -->
        <div class="form-group">
          <label for="title">Book Title</label>
          <input
            id="title"
            type="text"
            [(ngModel)]="book.title"
            name="title"
            placeholder="Enter book title"
            data-testid="input-title"
            (blur)="validateField('title')"
            (input)="validateField('title')"
            class="form-control"
            [class.error]="errors.title"
          />
          <div class="error-message" data-testid="error-title" *ngIf="errors.title">
            {{ errors.title }}
          </div>
        </div>

        <!-- Author Field -->
        <div class="form-group">
          <label for="author">Author Name</label>
          <input
            id="author"
            type="text"
            [(ngModel)]="book.author"
            name="author"
            placeholder="Enter author name"
            data-testid="input-author"
            (blur)="validateField('author')"
            (input)="validateField('author')"
            class="form-control"
            [class.error]="errors.author"
          />
          <div class="error-message" data-testid="error-author" *ngIf="errors.author">
            {{ errors.author }}
          </div>
        </div>

        <!-- ISBN Field -->
        <div class="form-group">
          <label for="isbn">ISBN Number</label>
          <input
            id="isbn"
            type="text"
            [(ngModel)]="book.isbn"
            name="isbn"
            placeholder="Enter 13-digit ISBN number"
            data-testid="input-isbn"
            (blur)="validateField('isbn')"
            (input)="validateField('isbn')"
            class="form-control"
            [class.error]="errors.isbn"
          />
          <div class="error-message" data-testid="error-isbn" *ngIf="errors.isbn">
            {{ errors.isbn }}
          </div>
        </div>

        <!-- Publication Date Field -->
        <div class="form-group">
          <label for="publication_date">Publication Date</label>
          <input
            id="publication_date"
            type="date"
            [(ngModel)]="book.publication_date"
            name="publication_date"
            data-testid="input-publication-date"
            (blur)="validateField('publication_date')"
            (change)="validateField('publication_date')"
            class="form-control"
            [class.error]="errors.publication_date"
          />
          <div class="error-message" data-testid="error-publication-date" *ngIf="errors.publication_date">
            {{ errors.publication_date }}
          </div>
        </div>

        <!-- Number of Pages Field -->
        <div class="form-group">
          <label for="number_of_pages">Number of Pages</label>
          <input
            id="number_of_pages"
            type="number"
            [(ngModel)]="book.number_of_pages"
            name="number_of_pages"
            placeholder="Enter number of pages"
            data-testid="input-pages"
            (blur)="validateField('number_of_pages')"
            (input)="validateField('number_of_pages')"
            class="form-control"
            [class.error]="errors.number_of_pages"
          />
          <div class="error-message" data-testid="error-pages" *ngIf="errors.number_of_pages">
            {{ errors.number_of_pages }}
          </div>
        </div>

        <!-- Submit Button -->
        <button
          type="submit"
          data-testid="btn-submit-book"
          [disabled]="!isFormValid()"
          class="submit-button"
        >
          Add Book
        </button>
      </form>

      <!-- Book Data Grid -->
      <div class="data-grid-container">
        <h2>Book List</h2>
        <table class="data-grid" data-testid="data-grid-books">
          <thead>
            <tr>
              <th>ID</th>
              <th>Title</th>
              <th>Author</th>
              <th>ISBN</th>
              <th>Publication Date</th>
              <th>Pages</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let book of books" [attr.data-testid]="'data-grid-row-' + book.id">
              <td [attr.data-testid]="'data-grid-cell-id-' + book.id">{{ book.id }}</td>
              <td [attr.data-testid]="'data-grid-cell-title-' + book.id">{{ book.title }}</td>
              <td [attr.data-testid]="'data-grid-cell-author-' + book.id">{{ book.author }}</td>
              <td [attr.data-testid]="'data-grid-cell-isbn-' + book.id">{{ book.isbn }}</td>
              <td [attr.data-testid]="'data-grid-cell-publication-date-' + book.id">{{ book.publication_date }}</td>
              <td [attr.data-testid]="'data-grid-cell-pages-' + book.id">{{ book.number_of_pages }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `,
  styles: [`
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    }

    h1 {
      color: #333;
      margin-bottom: 30px;
    }

    h2 {
      color: #555;
      margin-bottom: 20px;
    }

    .book-form {
      background: #f9f9f9;
      padding: 30px;
      border-radius: 8px;
      margin-bottom: 40px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .form-group {
      margin-bottom: 20px;
    }

    label {
      display: block;
      margin-bottom: 5px;
      font-weight: 500;
      color: #555;
    }

    .form-control {
      width: 100%;
      padding: 10px 12px;
      border: 2px solid #ddd;
      border-radius: 4px;
      font-size: 16px;
      transition: border-color 0.3s;
    }

    .form-control:focus {
      outline: none;
      border-color: #4CAF50;
    }

    .form-control.error {
      border-color: #f44336;
    }

    .error-message {
      color: #f44336;
      font-size: 14px;
      margin-top: 5px;
    }

    .submit-button {
      background-color: #4CAF50;
      color: white;
      padding: 12px 24px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s;
    }

    .submit-button:hover:not(:disabled) {
      background-color: #45a049;
    }

    .submit-button:disabled {
      background-color: #ccc;
      cursor: not-allowed;
    }

    .data-grid-container {
      background: #f9f9f9;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .data-grid {
      width: 100%;
      border-collapse: collapse;
      background: white;
    }

    .data-grid th {
      background-color: #4CAF50;
      color: white;
      padding: 12px;
      text-align: left;
      font-weight: 500;
    }

    .data-grid td {
      padding: 12px;
      border-bottom: 1px solid #ddd;
    }

    .data-grid tr:nth-child(even) {
      background-color: #f5f5f5;
    }

    .data-grid tr:hover {
      background-color: #e8f5e9;
    }
  `]
})
export class ClaudeComponent implements OnInit {
  book: Book = {
    title: '',
    author: '',
    isbn: '',
    publication_date: '',
    number_of_pages: 0
  };

  books: Book[] = [];
  errors: ValidationErrors = {};

  private apiUrl = '/books';

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    // Set default publication date to today
    const today = new Date();
    this.book.publication_date = today.toISOString().split('T')[0];

    // Load existing books
    this.loadBooks();
  }

  loadBooks(): void {
    this.http.get<Book[]>(this.apiUrl).subscribe({
      next: (data) => {
        this.books = data;
      },
      error: (error) => {
        console.error('Error loading books:', error);
      }
    });
  }

  validateField(field: keyof Book): void {
    const value = this.book[field];

    switch (field) {
      case 'title':
        if (!value || value.toString().length < 2 || value.toString().length > 100) {
          this.errors.title = 'Title must be between 2 and 100 characters.';
        } else {
          delete this.errors.title;
        }
        break;

      case 'author':
        if (!value || value.toString().length < 2 || value.toString().length > 60) {
          this.errors.author = 'Author name must be between 2 and 60 characters.';
        } else {
          delete this.errors.author;
        }
        break;

      case 'isbn':
        if (!value || !/^\d{13}$/.test(value.toString())) {
          this.errors.isbn = 'ISBN must contain exactly 13 numeric digits.';
        } else {
          delete this.errors.isbn;
        }
        break;

      case 'publication_date':
        if (!value) {
          this.errors.publication_date = 'Publication Date is required.';
        } else {
          const selectedDate = new Date(value);
          const today = new Date();
          today.setHours(0, 0, 0, 0);
          if (selectedDate > today) {
            this.errors.publication_date = 'Publication Date cannot be in the future.';
          } else {
            delete this.errors.publication_date;
          }
        }
        break;

      case 'number_of_pages':
        const pages = Number(value);
        if (!value || pages < 1 || pages > 5000 || !Number.isInteger(pages)) {
          this.errors.number_of_pages = 'Number of pages must be between 1 and 5000.';
        } else {
          delete this.errors.number_of_pages;
        }
        break;
    }
  }

  validateAllFields(): void {
    const fields: (keyof Book)[] = ['title', 'author', 'isbn', 'publication_date', 'number_of_pages'];
    fields.forEach(field => this.validateField(field));
  }

  isFormValid(): boolean {
    this.validateAllFields();
    return Object.keys(this.errors).length === 0 &&
           this.book.title !== '' &&
           this.book.author !== '' &&
           this.book.isbn !== '' &&
           this.book.publication_date !== '' &&
           this.book.number_of_pages > 0;
  }

  onSubmit(): void {
    if (!this.isFormValid()) {
      return;
    }

    this.http.post<Book>(this.apiUrl, this.book).subscribe({
      next: (newBook) => {
        // Add new book to the beginning of the list
        this.books.unshift(newBook);

        // Clear form
        this.book = {
          title: '',
          author: '',
          isbn: '',
          publication_date: new Date().toISOString().split('T')[0],
          number_of_pages: 0
        };

        // Clear errors
        this.errors = {};
      },
      error: (error) => {
        console.error('Error creating book:', error);
      }
    });
  }
}

// clients/react/src/claude.jsx
import React, { useState, useEffect } from 'react';

const Claude = () => {
  const [books, setBooks] = useState([]);
  const [formData, setFormData] = useState({
    title: '',
    author: '',
    isbn: '',
    publication_date: new Date().toISOString().split('T')[0],
    number_of_pages: ''
  });
  const [errors, setErrors] = useState({});
  const [touched, setTouched] = useState({});

  // Fetch books on component mount
  useEffect(() => {
    fetchBooks();
  }, []);

  const fetchBooks = async () => {
    try {
      const response = await fetch('/books');
      const data = await response.json();
      setBooks(data);
    } catch (error) {
      console.error('Error fetching books:', error);
    }
  };

  // Validation rules
  const validateField = (name, value) => {
    switch (name) {
      case 'title':
        if (!value) return 'Title is required';
        if (value.length < 2 || value.length > 100) {
          return 'Title must be between 2 and 100 characters.';
        }
        return '';
      
      case 'author':
        if (!value) return 'Author is required';
        if (value.length < 2 || value.length > 60) {
          return 'Author name must be between 2 and 60 characters.';
        }
        return '';
      
      case 'isbn':
        if (!value) return 'ISBN is required';
        if (!/^\d{13}$/.test(value)) {
          return 'ISBN must contain exactly 13 numeric digits.';
        }
        return '';
      
      case 'publication_date':
        if (!value) return 'Publication date is required';
        const selectedDate = new Date(value);
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        if (selectedDate > today) {
          return 'Publication Date cannot be in the future.';
        }
        return '';
      
      case 'number_of_pages':
        if (!value) return 'Number of pages is required';
        const pages = parseInt(value);
        if (!Number.isInteger(pages) || pages < 1 || pages > 5000) {
          return 'Number of pages must be between 1 and 5000.';
        }
        return '';
      
      default:
        return '';
    }
  };

  // Validate all fields
  const validateForm = () => {
    const newErrors = {};
    Object.keys(formData).forEach(field => {
      const error = validateField(field, formData[field]);
      if (error) newErrors[field] = error;
    });
    return newErrors;
  };

  // Check if form is valid
  const isFormValid = () => {
    const currentErrors = validateForm();
    return Object.keys(currentErrors).length === 0 && 
           Object.values(formData).every(value => value !== '');
  };

  // Handle input change
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    
    // Validate on change if field has been touched
    if (touched[name]) {
      setErrors(prev => ({ ...prev, [name]: validateField(name, value) }));
    }
  };

  // Handle input blur
  const handleBlur = (e) => {
    const { name, value } = e.target;
    setTouched(prev => ({ ...prev, [name]: true }));
    setErrors(prev => ({ ...prev, [name]: validateField(name, value) }));
  };

  // Handle form submission
  const handleSubmit = async () => {
    // Validate all fields
    const formErrors = validateForm();
    if (Object.keys(formErrors).length > 0) {
      setErrors(formErrors);
      return;
    }

    try {
      const response = await fetch('/books', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...formData,
          number_of_pages: parseInt(formData.number_of_pages)
        })
      });

      if (response.ok) {
        const newBook = await response.json();
        setBooks([newBook, ...books]);
        
        // Clear form
        setFormData({
          title: '',
          author: '',
          isbn: '',
          publication_date: new Date().toISOString().split('T')[0],
          number_of_pages: ''
        });
        setErrors({});
        setTouched({});
      }
    } catch (error) {
      console.error('Error submitting book:', error);
    }
  };

  // Handle Enter key press on inputs
  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && isFormValid()) {
      handleSubmit();
    }
  };

  return (
    <div style={{ padding: '20px', maxWidth: '1200px', margin: '0 auto' }}>
      <h1>Book Management System</h1>
      
      {/* Book Entry Form */}
      <div style={{ marginBottom: '40px', background: '#f5f5f5', padding: '20px', borderRadius: '8px' }}>
        <h2>Add New Book</h2>
        
        <div style={{ marginBottom: '20px' }}>
          <label htmlFor="title" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>
            Book Title
          </label>
          <input
            type="text"
            id="title"
            name="title"
            data-testid="input-title"
            placeholder="Enter book title"
            value={formData.title}
            onChange={handleChange}
            onBlur={handleBlur}
            onKeyPress={handleKeyPress}
            style={{ width: '100%', padding: '8px', border: '1px solid #ddd', borderRadius: '4px' }}
          />
          {errors.title && (
            <div data-testid="error-title" style={{ color: 'red', fontSize: '14px', marginTop: '5px' }}>
              {errors.title}
            </div>
          )}
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label htmlFor="author" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>
            Author Name
          </label>
          <input
            type="text"
            id="author"
            name="author"
            data-testid="input-author"
            placeholder="Enter author name"
            value={formData.author}
            onChange={handleChange}
            onBlur={handleBlur}
            onKeyPress={handleKeyPress}
            style={{ width: '100%', padding: '8px', border: '1px solid #ddd', borderRadius: '4px' }}
          />
          {errors.author && (
            <div data-testid="error-author" style={{ color: 'red', fontSize: '14px', marginTop: '5px' }}>
              {errors.author}
            </div>
          )}
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label htmlFor="isbn" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>
            ISBN Number
          </label>
          <input
            type="text"
            id="isbn"
            name="isbn"
            data-testid="input-isbn"
            placeholder="Enter 13-digit ISBN number"
            value={formData.isbn}
            onChange={handleChange}
            onBlur={handleBlur}
            onKeyPress={handleKeyPress}
            style={{ width: '100%', padding: '8px', border: '1px solid #ddd', borderRadius: '4px' }}
          />
          {errors.isbn && (
            <div data-testid="error-isbn" style={{ color: 'red', fontSize: '14px', marginTop: '5px' }}>
              {errors.isbn}
            </div>
          )}
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label htmlFor="publication_date" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>
            Publication Date
          </label>
          <input
            type="date"
            id="publication_date"
            name="publication_date"
            data-testid="input-publication-date"
            value={formData.publication_date}
            onChange={handleChange}
            onBlur={handleBlur}
            onKeyPress={handleKeyPress}
            style={{ width: '100%', padding: '8px', border: '1px solid #ddd', borderRadius: '4px' }}
          />
          {errors.publication_date && (
            <div data-testid="error-publication-date" style={{ color: 'red', fontSize: '14px', marginTop: '5px' }}>
              {errors.publication_date}
            </div>
          )}
        </div>

        <div style={{ marginBottom: '20px' }}>
          <label htmlFor="number_of_pages" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>
            Number of Pages
          </label>
          <input
            type="number"
            id="number_of_pages"
            name="number_of_pages"
            data-testid="input-pages"
            placeholder="Enter number of pages"
            value={formData.number_of_pages}
            onChange={handleChange}
            onBlur={handleBlur}
            onKeyPress={handleKeyPress}
            style={{ width: '100%', padding: '8px', border: '1px solid #ddd', borderRadius: '4px' }}
          />
          {errors.number_of_pages && (
            <div data-testid="error-pages" style={{ color: 'red', fontSize: '14px', marginTop: '5px' }}>
              {errors.number_of_pages}
            </div>
          )}
        </div>

        <button
          onClick={handleSubmit}
          data-testid="btn-submit-book"
          disabled={!isFormValid()}
          style={{
            padding: '10px 20px',
            background: isFormValid() ? '#007bff' : '#cccccc',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
            cursor: isFormValid() ? 'pointer' : 'not-allowed',
            fontSize: '16px',
            fontWeight: 'bold'
          }}
        >
          Add Book
        </button>
      </div>

      {/* Book Data Grid */}
      <div>
        <h2>Book List</h2>
        <div data-testid="data-grid-books" style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', border: '1px solid #ddd' }}>
            <thead>
              <tr style={{ backgroundColor: '#f8f9fa' }}>
                <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>ID</th>
                <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Title</th>
                <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Author</th>
                <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>ISBN</th>
                <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Publication Date</th>
                <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Pages</th>
              </tr>
            </thead>
            <tbody>
              {books.map(book => (
                <tr key={book.id} data-testid={`data-grid-row-${book.id}`} style={{ borderBottom: '1px solid #ddd' }}>
                  <td style={{ padding: '12px' }} data-testid={`data-grid-cell-id-${book.id}`}>
                    {book.id}
                  </td>
                  <td style={{ padding: '12px' }} data-testid={`data-grid-cell-title-${book.id}`}>
                    {book.title}
                  </td>
                  <td style={{ padding: '12px' }} data-testid={`data-grid-cell-author-${book.id}`}>
                    {book.author}
                  </td>
                  <td style={{ padding: '12px' }} data-testid={`data-grid-cell-isbn-${book.id}`}>
                    {book.isbn}
                  </td>
                  <td style={{ padding: '12px' }} data-testid={`data-grid-cell-publication-date-${book.id}`}>
                    {book.publication_date}
                  </td>
                  <td style={{ padding: '12px' }} data-testid={`data-grid-cell-pages-${book.id}`}>
                    {book.number_of_pages}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {books.length === 0 && (
            <div style={{ textAlign: 'center', padding: '40px', color: '#666' }}>
              No books found. Add your first book using the form above.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Claude;
